const express = require("express");
const router = express.Router();
const auth = require("./auth");
const user = require("./user");
const message = require("./message");
const conversation = require("./conversation");
router.use("/auth", auth);
router.use("/user", user);
router.use("/message", message);
router.use("/conversation", conversation);
module.exports = router;
